# wrangler.toml
name = 'edge'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"                 #KV绑定名默认不可修改
id = "2853a5eda9dc4638a88edf75d28ac2ab"                                #KV数据库id
